jobs:
  include:
  - name: ansible-lint
    language: python
    install:
    - pip install ansible-lint
    - ansible-lint --version
    script:
    - cd ansible && ansible-lint .
  - name: cfn-lint
    language: python
    install:
    - pip install cfn-lint
    script:
    # https://github.com/aws-cloudformation/cfn-python-lint/issues/1425
    - cfn-lint -x E3012:strict=false -t cloudformation/*.yml
