---
# CloudFormation Stack for Tor Metrics Operational Monitoring
# This stack will only deploy on us-east-1 and will deploy in the metrics VPC
# aws cloudformation deploy --region us-east-1 --stack-name metrics-monitor --template-file metrics-monitor.yml --capabilities CAPABILITY_IAM
Description: "Tor Metrics Nagios instance"
AWSTemplateFormatVersion: 2010-09-09
Resources:
  MonitorInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !Select [ 0, !GetAZs ]
      ImageId: ami-01db78123b2b99496
      InstanceType: t2.micro
      SubnetId:
        Fn::ImportValue: 'MetricsSubnet'
      IamInstanceProfile: !Ref AlerterInstanceProfile
      KeyName: "irl yubikey 4"
      SecurityGroupIds:
        - Fn::ImportValue: 'MetricsInternetSecurityGroup'
        - Fn::ImportValue: 'MetricsPingableSecurityGroup'
        - Fn::ImportValue: 'MetricsHTTPSecurityGroup'
        - Fn::ImportValue: 'MetricsHTTPSSecurityGroup'
  AlertContact:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: "MetricsAlertNotification"
      Subscription:
        - Endpoint: "irl@torproject.org"
          Protocol: email
        - Endpoint: "karsten@torproject.org"
          Protocol: email
  AlerterInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref AlerterRole
  AlerterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: |
        {
          "Version":"2012-10-17",
          "Statement":[{
            "Effect":"Allow",
            "Principal": {
              "Service": ["ec2.amazonaws.com"]
            },
            "Action": "sts:AssumeRole"
          }]
        }
  AlerterPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: AlertPublishPolicy
      PolicyDocument:
        Statement:
          - Action: sns:Publish
            Effect: Allow
            Resource: !Ref AlertContact
        Version: '2012-10-17'
      Roles:
      - !Ref AlerterRole
  AlerterQueryPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: AlertQueryPolicy
      PolicyDocument:
        Statement:
          - Action: cloudformation:DescribeStackResources
            Effect: Allow
            Resource: !Ref AWS::StackId
        Version: '2012-10-17'
      Roles:
      - !Ref AlerterRole
