---
- name: clone the sources
  git:
    repo: https://git.torproject.org/check.git
    dest: /srv/check.torproject.org/check
  become: true
  become_user: check
- name: create a gopath directory
  file:
    path: /srv/check.torproject.org/go
    state: directory
  become: true
  become_user: check
- name: create systemd user directory for check
  file:
    path: /srv/check.torproject.org/.config/systemd/user
    state: directory
  become: true
  become_user: check
- name: get sources for go gettext
  shell:
    cmd: go get github.com/samuel/go-gettext/gettext
  become: true
  become_user: check
- name: update translations
  make:
    chdir: /srv/check.torproject.org/check
    target: i18n
  become: true
  become_user: check
- name: build
  make:
    chdir: /srv/check.torproject.org/check
    target: build
  become: true
  become_user: check
- name: install tor client torrc
  copy:
    src: torrc
    dest: /srv/check.torproject.org/torrc
  become: true
  become_user: check
- name: create tor data directory
  file:
    path: /srv/check.torproject.org/tordata
    state: directory
  become: true
  become_user: check
- name: install check update script
  copy:
    src: cpexits.sh
    dest: "/srv/check.torproject.org/cpexits.sh"
  become: true
  become_user: check
- name: install systemd units
  copy:
    src: "{{ item }}"
    dest: /srv/check.torproject.org/.config/systemd/user/
    owner: check
    group: check
    mode: 0644
  with_items:
    - check.service
    - checktor.service
    - checkupdate.service
    - checkupdate.timer
  become: true
  become_user: check
- name: enable and start services and timers
  systemd:
    scope: user
    name: "{{ item }}"
    state: started
    enabled: yes
    daemon_reload: yes
  with_items:
    - check.service
    - checktor.service
    - checkupdate.timer
  become: yes
  become_user: check
