---
- name: clone the sources
  git:
    repo: https://git.torproject.org/check.git
    dest: /srv/check.torproject.org/check
  become: true
  become_user: check
- name: create a gopath directory
  file:
    path: /srv/check.torproject.org/go
    state: directory
  become: true
  become_user: check
- name: create systemd user directory for check
  file:
    path: /srv/check.torproject.org/.config/systemd/user
    state: directory
  become: true
  become_user: check
- name: get sources for go gettext
  shell:
    cmd: go get github.com/samuel/go-gettext/gettext
  become: true
  become_user: check
- name: update translations
  make:
    chdir: /srv/check.torproject.org/check
    target: i18n
  become: true
  become_user: check
- name: build
  make:
    chdir: /srv/check.torproject.org/check
    target: build
  become: true
  become_user: check
- name: install tor client torrc
  copy:
    src: torrc
    dest: /srv/check.torproject.org/torrc
  become: true
  become_user: check
- name: create tor data directory
  file:
    path: /srv/check.torproject.org/tordata
    state: directory
  become: true
  become_user: check
- name: install tor client service file
  copy:
    src: checktor.service
    dest: "/srv/check.torproject.org/.config/systemd/user/checktor.service"
  become: true
  become_user: check
- name: enable and start tor client service
  systemd:
    scope: user
    name: checktor
    state: started
    enabled: yes
    daemon_reload: yes
  become: yes
  become_user: check
