---
- name: create exit scanner application directory
  file:
    path: /srv/tordnsel.torproject.org/exitscanner
    state: directory
  become: true
  become_user: tordnsel
- name: clone the sources
  git:
    repo: https://github.com/NullHypothesis/exitmap.git
    dest: /srv/tordnsel.torproject.org/exitscanner/exitmap
  become: true
  become_user: tordnsel
  notify: restart exit scanner
- name: install the ipscan module
  copy:
    src: ipscan.py
    dest: /srv/tordnsel.torproject.org/exitscanner/exitmap/src/modules/ipscan.py
    mode: 0755
  become: true
  become_user: tordnsel
  notify: restart exit scanner
- name: install the exit scanner script
  copy:
    src: exitscan.py
    dest: /srv/tordnsel.torproject.org/exitscanner/exitscan.py
    mode: 0755
  become: true
  become_user: tordnsel
  notify: restart exit scanner
- name: create systemd user directory for exitscanner
  file:
    path: /srv/tordnsel.torproject.org/.config/systemd/user
    state: directory
  become: true
  become_user: tordnsel
- name: create exit lists directory
  file:
    path: /srv/tordnsel.torproject.org/lists
    state: directory
  become: true
  become_user: tordnsel
- name: install exit scanner service file
  copy:
    src: exitscanner.service
    dest: "/srv/tordnsel.torproject.org/.config/systemd/user/exitscanner.service"
  become: true
  become_user: tordnsel
  notify: restart exit scanner
- name: enable and start exitscanner service
  systemd:
    scope: user
    name: exitscanner
    state: started
    enabled: yes
    daemon_reload: true
  become: yes
  become_user: tordnsel
