---
- name: disable system tor
  systemd:
    name: tor.service
    enabled: false
    state: stopped
  become: true
- name: install stem for py2 from backports
  apt:
    pkg: python-stem
    state: latest
    default_release: buster-backports
  become: true
- name: install stem for py3 from backports
  apt:
    pkg: python3-stem
    state: latest
    default_release: buster-backports
  become: true
- name: install exitmap requirements
  apt:
    pkg:
      - git
      - python-dnspython
      - curl
      - gettext
      - golang-go
      - build-essential
      - python-dateutil
    update_cache: yes
  become: yes
- name: create check account
  user:
    name: check
    comment: "Check Service User"
    uid: 1507
    state: present
  become: yes
- name: create tordnsel account
  user:
    name: tordnsel
    comment: "Exit Scanner Service User"
    uid: 1532
    state: present
  become: yes
- name: create service directory
  file:
    path: /srv/tordnsel.torproject.org
    state: directory
  become: yes
- name: link home directories /home
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: yes
  with_items:
    - { src: /home/tordnsel, dest: /srv/tordnsel.torproject.org }
    - { src: /home/check, dest: /srv/check.torproject.org }
  become: yes
- name: create exit scanner runtime directory
  file:
    path: /srv/tordnsel.torproject.org/exitscanner
    owner: tordnsel
    group: tordnsel
    mode: 0755
    state: directory
  become: yes
- name: create check runtime directory
  file:
    path: /srv/tordnsel.torproject.org/check
    owner: check
    group: check
    mode: 0755
    state: directory
  become: yes
- name: enable lingering for service users
  shell: "loginctl enable-linger {{ item }}"
  with_items:
    - tordnsel
    - check
  become: yes
